server:
  port: 8089
debug:
  true

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://114.115.179.52:5432/openalex?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: openalex
    password: "@Genius2023"
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  #邮箱基本配置
  mail:
    #配置smtp服务主机地址
    host: smtp.qq.co
    #发送者邮箱
    username: 2379206341@qq.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: wzojhwrzyabgecaf
    #端口号465或587
    port: 465
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
    protocol: smtps

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
